name: dart2_tryparse
description: Dart 1 polyfills for Dart 2 tryParse() methods
version: 1.0.1+dart2
homepage: https://github.com/apptreesoftware/dart2_tryparse
author: john ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=2.0.0-dev.34.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
